version: '3.9'

services:
  postgres:
    container_name: database_metropolitan
    image: metropolitan_postgres:v1
    ports:
      - 5433:5432
    volumes:
      - ${USERPROFILE}/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=metropolitan_db